/*
 * Decompiled with CFR 0.152.
 */
package manthe;

import a.a;
import java.util.HashMap;
import javassist.bytecode.CodeAttribute$RuntimeCopyException;
import manthe.V;
import manthe.cy_0;
import manthe.gJ;
import manthe.on;

public class A5 {
    public static Class aq;
    public static Class d0;
    public static Class ba;
    public static Class cc;
    public static Class u;
    public static Class aE;
    public static Class y;
    public static Class dC;
    public static Class aT;
    public static Class bu;
    public static Class dr;
    public static Class ci;
    public static Class r;
    public static Class c1;
    public static Class b6;
    public static Class cF;
    public static Class bv;
    public static Class l;
    public static Class d1;
    public static Class aZ;
    public static Class a9;
    public static Class J;
    public static Class b5;
    public static Class ch;
    public static Class dS;
    public static Class aj;
    public static Class bT;
    public static Class cg;
    public static Class dx;
    public static Class bt;
    public static Class aF;
    public static Class aS;
    public static Class L;
    public static Class a;
    public static Class P;
    public static Class aV;
    public static Class dI;
    public static Class cl;
    public static Class ah;
    public static Class dK;
    public static Class F;
    public static Class an;
    public static Class c0;
    public static Class bO;
    public static Class c_;
    public static Class a4;
    public static Class aa;
    public static Class dH;
    public static Class dl;
    public static Class ai;
    public static Class dX;
    public static Class g;
    public static Class ca;
    public static Class aD;
    public static Class cL;
    public static Class Y;
    public static Class dn;
    public static Class ae;
    public static Class n;
    public static Class bb;
    public static Class bX;
    public static Class bK;
    public static Class c4;
    public static Class dV;
    public static Class aH;
    public static Class c2;
    public static Class dk;
    public static Class dj;
    public static Class aU;
    public static Class f;
    public static Class aC;
    public static Class bD;
    public static Class s;
    public static Class aN;
    public static Class ap;
    public static Class dq;
    public static Class o;
    public static Class H;
    public static Class ar;
    public static Class b9;
    public static Class cT;
    public static Class cW;
    public static Class cs;
    public static Class dJ;
    public static Class cj;
    public static Class dp;
    public static Class av;
    public static Class aR;
    public static Class al;
    public static Class be;
    public static Class dt;
    public static Class am;
    public static Class N;
    public static Class dN;
    public static Class br;
    public static Class du;
    public static Class d2;
    public static Class aK;
    public static Class cE;
    public static Class k;
    public static Class b;
    public static Class dA;
    public static Class bU;
    public static Class c6;
    public static Class cN;
    public static Class a1;
    public static Class bW;
    public static Class aQ;
    public static Class dh;
    public static Class cr;
    public static Class dv;
    public static Class au;
    public static Class dZ;
    public static Class cK;
    public static Class bQ;
    public static Class cZ;
    public static Class aP;
    public static Class cX;
    public static Class bx;
    public static Class dL;
    public static Class cf;
    public static Class dW;
    public static Class ay;
    public static Class a0;
    public static Class dT;
    public static Class as;
    public static Class q;
    public static Class dF;
    public static Class at;
    public static Class ck;
    public static Class a2;
    public static Class ag;
    public static Class bj;
    public static Class bw;
    public static Class bz;
    public static Class p;
    public static Class ad;
    public static Class dG;
    public static Class aX;
    public static Class c5;
    public static Class c9;
    public static Class bf;
    public static Class bl;
    public static Class bn;
    public static Class cI;
    public static Class cA;
    public static Class af;
    public static Class cS;
    public static Class bM;
    public static Class db;
    public static Class e;
    public static Class aw;
    public static Class aG;
    public static Class dU;
    public static Class cY;
    public static Class w;
    public static Class az;
    public static Class h;
    public static Class Q;
    public static Class S;
    public static Class bB;
    public static Class ce;
    public static Class c;
    public static Class dw;
    public static Class cV;
    public static Class cM;
    public static Class bE;
    public static Class cv;
    public static Class aL;
    public static Class ao;
    public static Class aY;
    public static Class aA;
    public static Class bY;
    public static Class cP;
    public static Class b0;
    public static Class T;
    public static Class a8;
    public static Class cw;
    public static Class bq;
    public static Class ds;
    public static Class b_;
    public static Class aW;
    public static Class b4;
    public static Class cH;
    public static Class d;
    public static Class W;
    public static Class j;
    public static Class cp;
    public static Class cq;
    public static Class dQ;
    public static Class cU;
    public static Class bN;
    public static Class aB;
    public static Class bF;
    public static Class a5;
    public static Class a3;
    public static Class ax;
    public static Class b7;
    public static Class de;
    public static Class bG;
    public static Class b3;
    public static Class aI;
    public static Class bR;
    public static Class cu;
    public static Class dg;
    public static Class b1;
    public static Class cJ;
    public static Class ct;
    public static Class cQ;
    public static Class R;
    public static Class bk;
    public static Class bp;
    public static Class d3;
    public static Class bI;
    public static Class bJ;
    public static Class U;
    public static Class b2;
    public static Class bm;
    public static Class z;
    public static Class cz;
    public static Class dE;
    public static Class G;
    public static Class bH;
    public static Class ab;
    public static Class a6;
    public static Class cm;
    public static Class cy;
    public static Class a_;
    public static Class E;
    public static Class cb;
    public static Class x;
    public static Class b8;
    public static Class c8;
    public static Class bd;
    public static Class K;
    public static Class V;
    public static Class bL;
    public static Class dB;
    public static Class cG;
    public static Class bZ;
    public static Class cB;
    public static Class a7;
    public static Class dd;
    public static Class dD;
    public static Class bs;
    public static Class c3;
    public static Class M;
    public static Class bh;
    public static Class bi;
    public static Class bP;
    public static Class da;
    public static Class m;
    public static Class cx;
    public static Class d4;
    public static Class i;
    public static Class by;
    public static Class aJ;
    public static Class cD;
    public static Class ac;
    public static Class cn;
    public static Class B;
    public static Class O;
    public static Class cC;
    public static Class dR;
    public static Class dP;
    public static Class bV;
    public static Class t;
    public static Class dz;
    public static Class di;
    public static Class A;
    public static Class bo;
    public static Class bc;
    public static Class bS;
    public static Class dy;
    public static Class dM;
    public static Class D;
    public static Class ak;
    public static Class bC;
    public static Class co;
    public static String bg;
    public static String dY;
    public static Class bA;
    public static Class cR;
    public static Class aO;
    public static Class cO;
    public static Class dm;
    public static Class cd;
    public static Class c7;
    public static Class dc;
    public static Class I;
    public static Class dO;
    public static Class X;
    public static Class Z;
    public static Class df;
    public static Class aM;
    public static HashMap<String, String> C;
    private static boolean v;

    private static Class a(String string) {
        if (on.p.h()) {
            if (string.contains("net/minecraftforge") || string.contains("cpw/mods/")) {
                return null;
            }
            Class<?> clazz = a.a.gvc(string);
            if (clazz != null) {
                C.put(clazz.getName(), string);
            }
            return clazz;
        }
        return a.a.gc(string);
    }

    public static void a() {
        block19: {
            int n6;
            block17: {
                block18: {
                    int n10;
                    block16: {
                        int n11;
                        block11: {
                            block12: {
                                block15: {
                                    int n12;
                                    block13: {
                                        block14: {
                                            block10: {
                                                int n13;
                                                block8: {
                                                    block9: {
                                                        co = A5.a("java/lang/System");
                                                        n10 = gJ.b();
                                                        n13 = manthe.V.c();
                                                        if (n10 == 0) break block8;
                                                        if (n13 <= 13) break block9;
                                                        bg = "net/minecraftforge/";
                                                        if (n10 != 0) break block10;
                                                        cy_0.b(!cy_0.c());
                                                    }
                                                    n13 = 876;
                                                }
                                                bg = a.a.cs(n13);
                                            }
                                            dY = bg.replace("/", ".");
                                            dd = A5.a("net/minecraft/client/renderer/GlStateManager");
                                            dD = A5.a("net/minecraft/world/IWorldNameable");
                                            bs = A5.a("net/minecraftforge/client/event/EntityViewRenderEvent");
                                            c3 = A5.a("net/minecraftforge/client/event/EntityViewRenderEvent$FogDensity");
                                            M = A5.a("net/minecraftforge/client/event/EntityViewRenderEvent$RenderFogEvent");
                                            bh = A5.a("net/minecraftforge/client/event/EntityViewRenderEvent$FogColors");
                                            bP = A5.a("net/minecraftforge/event/entity/player/PlayerEvent");
                                            da = A5.a("net/minecraftforge/event/entity/player/ItemTooltipEvent");
                                            m = A5.a("net/minecraftforge/event/entity/player/PlayerInteractEvent");
                                            cx = A5.a("net/minecraftforge/client/event/RenderHandEvent");
                                            d4 = A5.a("net/minecraftforge/event/entity/player/PlayerEvent$NameFormat");
                                            i = A5.a("net/minecraftforge/event/entity/PlaySoundAtEntityEvent");
                                            by = A5.a("net/minecraftforge/client/event/RenderGameOverlayEvent");
                                            a7 = A5.a("net/minecraftforge/event/entity/EntityEvent");
                                            aq = A5.a("net/minecraftforge/common/ForgeVersion");
                                            dH = A5.a("net/minecraftforge/client/event/MouseEvent");
                                            dl = A5.a("net/minecraftforge/common/MinecraftForge");
                                            b = A5.a("net/minecraftforge/client/IRenderHandler");
                                            dA = A5.a("net/minecraftforge/client/event/RenderBlockOverlayEvent");
                                            bM = A5.a("net/minecraftforge/client/event/GuiScreenEvent");
                                            db = A5.a("net/minecraftforge/client/event/GuiScreenEvent$DrawScreenEvent");
                                            e = A5.a("net/minecraftforge/client/event/GuiScreenEvent$DrawScreenEvent$Pre");
                                            aw = A5.a("net/minecraftforge/client/event/GuiScreenEvent$DrawScreenEvent$Post");
                                            cB = A5.a("net/minecraftforge/event/entity/living/LivingEvent");
                                            w = A5.a("net/minecraftforge/client/event/ClientChatReceivedEvent");
                                            bB = A5.a("net/minecraftforge/client/event/RenderLivingEvent");
                                            bi = A5.a("net/minecraftforge/client/event/GuiOpenEvent");
                                            aJ = A5.a("org/lwjgl/input/Mouse");
                                            cD = A5.a("org/lwjgl/input/Keyboard");
                                            ac = A5.a("net/minecraft/client/gui/GuiIngame");
                                            cn = A5.a("net/minecraft/client/gui/GuiDownloadTerrain");
                                            B = A5.a("net/minecraft/client/gui/GuiMainMenu");
                                            O = A5.a("net/minecraft/client/gui/GuiMultiplayer");
                                            bc = A5.a("net/minecraft/entity/monster/IMob");
                                            d0 = A5.a("net/minecraft/client/Minecraft");
                                            ba = A5.a("net/minecraft/entity/Entity");
                                            cc = A5.a("net/minecraft/entity/player/EntityPlayer");
                                            u = A5.a("net/minecraft/client/entity/EntityPlayerSP");
                                            aE = A5.a("net/minecraft/client/gui/GuiScreen");
                                            y = A5.a("net/minecraft/client/gui/GuiChat");
                                            dC = A5.a("net/minecraft/client/gui/Gui");
                                            bu = A5.a("net/minecraft/util/Session");
                                            dr = A5.a("net/minecraft/client/settings/GameSettings");
                                            ci = A5.a("net/minecraft/client/settings/KeyBinding");
                                            r = A5.a("net/minecraft/world/World");
                                            c1 = A5.a("net/minecraft/world/WorldProvider");
                                            b6 = A5.a("net/minecraft/client/multiplayer/WorldClient");
                                            cF = A5.a("net/minecraft/entity/EntityLivingBase");
                                            l = A5.a("net/minecraft/client/gui/FontRenderer");
                                            d1 = A5.a("net/minecraft/util/MovementInput");
                                            aZ = A5.a("net/minecraft/client/multiplayer/PlayerControllerMP");
                                            a9 = A5.a("net/minecraft/client/renderer/EntityRenderer");
                                            J = A5.a("net/minecraft/entity/item/EntityItemFrame");
                                            b5 = A5.a("net/minecraft/entity/item/EntityFallingBlock");
                                            ch = A5.a("net/minecraft/entity/item/EntityItem");
                                            dS = A5.a("net/minecraft/client/gui/ScaledResolution");
                                            aj = A5.a("net/minecraft/entity/player/InventoryPlayer");
                                            bT = A5.a("net/minecraft/item/ItemStack");
                                            cg = A5.a("net/minecraft/item/Item");
                                            dx = A5.a("net/minecraft/item/ItemPotion");
                                            bt = A5.a("net/minecraft/client/gui/inventory/GuiContainer");
                                            aF = A5.a("net/minecraft/inventory/Slot");
                                            aS = A5.a("net/minecraft/inventory/Container");
                                            L = A5.a("net/minecraft/client/entity/EntityOtherPlayerMP");
                                            a = A5.a("net/minecraft/client/renderer/entity/RenderManager");
                                            P = A5.a("net/minecraft/entity/monster/EntityMob");
                                            aV = A5.a("net/minecraft/entity/boss/EntityDragon");
                                            dI = A5.a("net/minecraft/entity/monster/EntityGhast");
                                            cl = A5.a("net/minecraft/entity/monster/EntityGolem");
                                            ah = A5.a("net/minecraft/entity/passive/EntityAnimal");
                                            dK = A5.a("net/minecraft/entity/monster/EntitySlime");
                                            F = A5.a("net/minecraft/block/Block");
                                            an = A5.a("net/minecraft/item/ItemEnderPearl");
                                            c0 = A5.a("net/minecraft/item/ItemFood");
                                            bO = A5.a("net/minecraft/item/ItemSword");
                                            c_ = A5.a("net/minecraft/client/renderer/Tessellator");
                                            ai = A5.a("net/minecraft/client/renderer/texture/TextureManager");
                                            dX = A5.a("net/minecraft/client/resources/IResourceManager");
                                            g = A5.a("net/minecraft/client/shader/Framebuffer");
                                            ca = A5.a("net/minecraft/util/ResourceLocation");
                                            aD = A5.a("net/minecraft/client/shader/ShaderGroup");
                                            cL = A5.a("net/minecraft/init/Blocks");
                                            Y = A5.a("net/minecraft/block/material/Material");
                                            dn = A5.a("net/minecraft/block/BlockGrass");
                                            ae = A5.a("net/minecraft/block/BlockLeaves");
                                            n = A5.a("net/minecraft/block/BlockFence");
                                            bb = A5.a("net/minecraft/block/BlockWall");
                                            bX = A5.a("net/minecraft/block/BlockFenceGate");
                                            bK = A5.a("net/minecraft/block/BlockChest");
                                            c4 = A5.a("net/minecraft/block/BlockContainer");
                                            dV = A5.a("net/minecraft/client/network/NetHandlerPlayClient");
                                            aH = A5.a("net/minecraft/network/Packet");
                                            c2 = A5.a("net/minecraft/potion/Potion");
                                            dk = A5.a("net/minecraft/potion/PotionEffect");
                                            dj = A5.a("net/minecraft/entity/passive/EntityAmbientCreature");
                                            aU = A5.a("net/minecraft/network/NetworkManager");
                                            f = A5.a("io/netty/channel/Channel");
                                            aC = A5.a("net/minecraft/network/INetHandler");
                                            bD = A5.a("io/netty/util/concurrent/GenericFutureListener");
                                            s = A5.a("net/minecraft/network/NetworkManager$InboundHandlerTuplePacketListener");
                                            aN = A5.a("net/minecraft/client/gui/inventory/GuiChest");
                                            ap = A5.a("net/minecraft/inventory/IInventory");
                                            dq = A5.a("net/minecraft/util/Timer");
                                            o = A5.a("net/minecraft/util/FoodStats");
                                            H = A5.a("net/minecraft/entity/ai/attributes/IAttributeInstance");
                                            ar = A5.a("net/minecraft/entity/ai/attributes/AttributeModifier");
                                            b9 = A5.a("net/minecraft/entity/ai/attributes/IAttribute");
                                            cT = A5.a("net/minecraft/entity/SharedMonsterAttributes");
                                            cW = A5.a("net/minecraft/item/ItemAxe");
                                            cs = A5.a("net/minecraft/entity/EntityCreature");
                                            dJ = A5.a("net/minecraft/scoreboard/Team");
                                            cj = A5.a("net/minecraft/client/settings/GameSettings$Options");
                                            dp = A5.a("net/minecraft/client/renderer/RenderGlobal");
                                            av = A5.a("net/minecraft/item/ItemBlock");
                                            aR = A5.a("com/mojang/authlib/yggdrasil/YggdrasilMinecraftSessionService");
                                            al = A5.a("com/mojang/authlib/GameProfile");
                                            be = A5.a("net/minecraft/item/ItemSnowball");
                                            dt = A5.a("net/minecraft/item/ItemEgg");
                                            am = A5.a("net/minecraft/tileentity/TileEntity");
                                            N = A5.a("net/minecraft/tileentity/TileEntityChest");
                                            dN = A5.a("net/minecraft/tileentity/TileEntityEnderChest");
                                            br = A5.a("net/minecraft/tileentity/TileEntityMobSpawner");
                                            du = A5.a("net/minecraft/tileentity/TileEntityHopper");
                                            d2 = A5.a("net/minecraft/tileentity/TileEntityFurnace");
                                            aK = A5.a("net/minecraft/tileentity/TileEntityDropper");
                                            cE = A5.a("net/minecraft/tileentity/TileEntityDispenser");
                                            k = A5.a("net/minecraft/tileentity/MobSpawnerBaseLogic");
                                            bU = A5.a("net/minecraft/item/ItemSoup");
                                            c6 = A5.a("net/minecraft/entity/player/PlayerCapabilities");
                                            cN = A5.a("net/minecraft/item/ItemArmor");
                                            a1 = A5.a("net/minecraft/enchantment/EnchantmentHelper");
                                            aQ = A5.a("net/minecraft/enchantment/EnchantmentHelper$ModifierDamage");
                                            bW = A5.a("net/minecraft/enchantment/EnchantmentHelper$IModifier");
                                            dh = A5.a("net/minecraft/enchantment/Enchantment");
                                            cr = A5.a("net/minecraft/nbt/NBTBase");
                                            dv = A5.a("net/minecraft/nbt/NBTTagList");
                                            au = A5.a("net/minecraft/nbt/NBTTagCompound");
                                            dZ = A5.a("net/minecraft/client/model/ModelRenderer");
                                            cK = A5.a("net/minecraft/entity/EnumCreatureAttribute");
                                            bQ = A5.a("net/minecraft/util/DamageSource");
                                            cZ = A5.a("net/minecraft/item/ItemBow");
                                            aP = A5.a("net/minecraft/item/ItemTool");
                                            cX = A5.a("net/minecraft/item/ItemFishingRod");
                                            bx = A5.a("net/minecraft/item/ItemGlassBottle");
                                            dL = A5.a("net/minecraft/item/ItemBucket");
                                            cf = A5.a("net/minecraft/item/ItemAppleGold");
                                            dW = A5.a("net/minecraft/item/ItemPickaxe");
                                            ay = A5.a("net/minecraft/item/ItemSpade");
                                            a0 = A5.a("net/minecraft/init/Items");
                                            dT = A5.a("net/minecraft/client/renderer/RenderHelper");
                                            as = A5.a("net/minecraft/network/play/INetHandlerPlayClient");
                                            q = A5.a("net/minecraft/util/MouseHelper");
                                            dF = A5.a("net/minecraft/world/chunk/Chunk");
                                            at = A5.a("net/minecraft/world/chunk/IChunkProvider");
                                            ck = A5.a("net/minecraft/client/renderer/texture/ITextureObject");
                                            a2 = A5.a("net/minecraft/block/BlockLiquid");
                                            ag = A5.a("net/minecraft/client/gui/inventory/GuiInventory");
                                            bj = A5.a("net/minecraft/client/renderer/entity/Render");
                                            bw = A5.a("net/minecraft/client/model/ModelBase");
                                            bz = A5.a("net/minecraft/client/model/ModelBiped");
                                            p = A5.a("net/minecraft/client/renderer/entity/RenderPlayer");
                                            aX = A5.a("net/minecraft/entity/projectile/EntityPotion");
                                            ad = A5.a("net/minecraft/entity/projectile/EntityFireball");
                                            dG = A5.a("net/minecraft/entity/projectile/EntityLargeFireball");
                                            c5 = A5.a("net/minecraft/entity/projectile/EntityFishHook");
                                            c9 = A5.a("net/minecraft/entity/projectile/EntityArrow");
                                            bf = A5.a("net/minecraft/entity/projectile/EntityThrowable");
                                            bl = A5.a("net/minecraft/entity/item/EntityTNTPrimed");
                                            bn = A5.a("net/minecraft/entity/IProjectile");
                                            cI = A5.a("net/minecraft/entity/monster/EntityEnderman");
                                            cA = A5.a("net/minecraft/entity/projectile/EntitySnowball");
                                            af = A5.a("net/minecraft/entity/item/EntityEnderPearl");
                                            cS = A5.a("net/minecraft/entity/projectile/EntityEgg");
                                            cC = A5.a("net/minecraft/client/entity/AbstractClientPlayer");
                                            aG = A5.a("net/minecraft/launchwrapper/LaunchClassLoader");
                                            dU = A5.a("net/minecraft/launchwrapper/Launch");
                                            cY = A5.a("io/netty/channel/ChannelHandlerContext");
                                            az = A5.a("net/minecraft/item/Item$ToolMaterial");
                                            h = A5.a("net/minecraft/item/ItemArmor$ArmorMaterial");
                                            Q = A5.a("net/minecraft/client/gui/inventory/GuiContainerCreative$CreativeSlot");
                                            S = A5.a("net/minecraft/client/gui/inventory/GuiContainerCreative");
                                            bS = A5.a("net/minecraft/network/ThreadQuickExitException");
                                            dy = A5.a("net/minecraft/creativetab/CreativeTabs");
                                            dM = A5.a("net/minecraft/server/integrated/IntegratedServer");
                                            D = A5.a("net/minecraft/client/multiplayer/ServerData");
                                            aY = A5.a("net/minecraft/util/EnumFacing");
                                            dR = A5.a("shadersmod/client/Shaders");
                                            bC = A5.a("net/minecraft/world/EnumSkyBlock");
                                            di = A5.a("net/minecraft/client/shader/ShaderUniform");
                                            A = A5.a("net/minecraft/client/shader/Shader");
                                            bo = A5.a("net/minecraft/client/shader/ShaderManager");
                                            dm = A5.a("net/minecraft/block/BlockBed");
                                            X = A5.a("net/minecraft/profiler/Profiler");
                                            n11 = manthe.V.c();
                                            if (n10 == 0) break block11;
                                            if (n11 <= 13) break block12;
                                            n12 = manthe.V.c();
                                            if (n10 == 0) break block13;
                                            if (n12 < 23) break block14;
                                            aL = A5.a("net/minecraft/util/math/Vec3i");
                                            ao = A5.a("net/minecraft/util/math/BlockPos");
                                            aA = A5.a("net/minecraft/block/state/IBlockState");
                                            bY = A5.a("net/minecraft/network/play/client/CPacketEntityAction$Action");
                                            cP = A5.a("net/minecraft/network/play/server/SPacketPlayerPosLook$EnumFlags");
                                            ak = A5.a("net/minecraft/block/BlockChest$Type");
                                            bV = A5.a("net/minecraft/client/renderer/block/model/IBakedModel");
                                            dP = A5.a("net/minecraft/util/BlockRenderLayer");
                                            if (n10 != 0) break block15;
                                        }
                                        aL = A5.a("net/minecraft/util/Vec3i");
                                        ao = A5.a("net/minecraft/util/BlockPos");
                                        aA = A5.a("net/minecraft/block/state/IBlockState");
                                        bY = A5.a("net/minecraft/network/play/client/C0BPacketEntityAction$Action");
                                        cP = A5.a("net/minecraft/network/play/server/S08PacketPlayerPosLook$EnumFlags");
                                        bV = A5.a("net/minecraft/client/resources/model/IBakedModel");
                                        n12 = 1086;
                                    }
                                    dP = A5.a(a.a.cs(n12));
                                }
                                T = A5.a("net/minecraft/client/network/NetworkPlayerInfo");
                                a4 = A5.a("net/minecraftforge/fml/common/eventhandler/Event");
                                aa = A5.a("net/minecraftforge/fml/common/eventhandler/EventBus");
                                ce = A5.a("net/minecraftforge/fml/common/gameevent/TickEvent");
                                dw = A5.a("net/minecraftforge/fml/common/gameevent/TickEvent$Phase");
                                c = A5.a("net/minecraftforge/fml/common/gameevent/TickEvent$RenderTickEvent");
                                cV = A5.a("net/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent");
                                cM = A5.a("net/minecraftforge/fml/common/gameevent/InputEvent$KeyInputEvent");
                                b0 = A5.a("net/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent");
                                a8 = A5.a("net/minecraft/entity/item/EntityArmorStand");
                                cw = A5.a("net/minecraft/client/renderer/vertex/VertexFormat");
                                bq = A5.a("net/minecraft/client/renderer/vertex/DefaultVertexFormats");
                                b_ = A5.a("net/minecraft/client/model/ModelPlayer");
                                b8 = A5.a("net/minecraft/world/IBlockAccess");
                                cm = A5.a("net/minecraft/util/EnumParticleTypes");
                                aT = A5.a("net/minecraft/client/gui/GuiPlayerTabOverlay");
                                cd = A5.a("net/minecraft/block/BlockBed$EnumPartType");
                                c7 = A5.a("net/minecraft/block/properties/IProperty");
                                dc = A5.a("net/minecraft/block/BlockDirectional");
                                I = A5.a("net/minecraft/block/properties/PropertyDirection");
                                dO = A5.a("net/minecraft/block/properties/PropertyEnum");
                                dg = A5.a("net/minecraft/client/renderer/chunk/SetVisibility");
                                b1 = A5.a("net/minecraft/client/renderer/chunk/VisGraph");
                                bv = A5.a("net/minecraft/client/renderer/BlockModelRenderer");
                                Z = A5.a("net/minecraft/client/renderer/GlStateManager$TextureState");
                                df = A5.a("net/minecraft/client/renderer/GlStateManager$BooleanState");
                                aM = A5.a("net/minecraft/client/renderer/GlStateManager$BlendState");
                                if (n10 != 0) break block16;
                            }
                            dz = A5.a("net/minecraft/util/IIcon");
                            t = A5.a("net/minecraft/client/renderer/RenderBlocks");
                            ds = A5.a("net/minecraft/command/IEntitySelector");
                            a4 = A5.a("cpw/mods/fml/common/eventhandler/Event");
                            aa = A5.a("cpw/mods/fml/common/eventhandler/EventBus");
                            ce = A5.a("cpw/mods/fml/common/gameevent/TickEvent");
                            dw = A5.a("cpw/mods/fml/common/gameevent/TickEvent$Phase");
                            cV = A5.a("cpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent");
                            c = A5.a("cpw/mods/fml/common/gameevent/TickEvent$RenderTickEvent");
                            cM = A5.a("cpw/mods/fml/common/gameevent/InputEvent$KeyInputEvent");
                            b0 = A5.a("cpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent");
                            n11 = 1125;
                        }
                        cv = A5.a(a.a.cs(n11));
                    }
                    n6 = manthe.V.c();
                    if (n10 == 0) break block17;
                    if (n6 < 23) break block18;
                    V = A5.a("net/minecraft/client/particle/ParticleEmitter");
                    aW = A5.a("net/minecraft/util/math/Vec3d");
                    b4 = A5.a("net/minecraft/util/math/AxisAlignedBB");
                    cH = A5.a("net/minecraft/util/math/RayTraceResult");
                    d = A5.a("net/minecraft/util/math/RayTraceResult$Type");
                    W = A5.a("net/minecraft/network/play/client/CPacketKeepAlive");
                    j = A5.a("net/minecraft/network/play/client/CPacketConfirmTransaction");
                    cp = A5.a("net/minecraft/network/play/client/CPacketAnimation");
                    cq = A5.a("net/minecraft/network/play/client/CPacketEntityAction");
                    dQ = A5.a("net/minecraft/network/play/client/CPacketChatMessage");
                    cU = A5.a("net/minecraft/network/play/client/CPacketUseEntity");
                    bN = A5.a("net/minecraft/network/play/client/CPacketPlayer");
                    aB = A5.a("net/minecraft/network/play/client/CPacketPlayerDigging");
                    bF = A5.a("net/minecraft/network/play/client/CPacketHeldItemChange");
                    a5 = A5.a("net/minecraft/network/play/client/CPacketPlayerAbilities");
                    a3 = A5.a("net/minecraft/network/play/client/CPacketCloseWindow");
                    ax = A5.a("net/minecraft/client/renderer/RenderItem");
                    b7 = A5.a("net/minecraft/network/play/client/CPacketUseEntity$Action");
                    de = A5.a("net/minecraft/entity/ai/attributes/AbstractAttributeMap");
                    bG = A5.a("net/minecraft/util/text/ITextComponent");
                    b3 = A5.a("net/minecraft/util/text/TextComponentString");
                    aI = A5.a("net/minecraft/util/text/Style");
                    bR = A5.a("net/minecraft/util/text/TextComponentTranslation");
                    cu = A5.a("net/minecraft/client/renderer/BufferBuilder");
                    ct = A5.a("net/minecraft/network/play/server/SPacketParticles");
                    cJ = A5.a("net/minecraft/network/play/server/SPacketExplosion");
                    cQ = A5.a("net/minecraft/network/play/server/SPacketEntityVelocity");
                    R = A5.a("net/minecraft/network/play/server/SPacketEntity");
                    bk = A5.a("net/minecraft/network/play/server/SPacketEntity$S16PacketEntityLook");
                    bp = A5.a("net/minecraft/network/play/server/SPacketEntityTeleport");
                    bI = A5.a("net/minecraft/network/play/server/SPacketBlockChange");
                    U = A5.a("net/minecraft/network/play/server/SPacketPlayerPosLook");
                    b2 = A5.a("net/minecraft/client/renderer/entity/RenderLivingBase");
                    bm = A5.a("net/minecraft/util/registry/RegistryNamespaced");
                    z = A5.a("net/minecraft/util/registry/RegistrySimple");
                    dE = A5.a("net/minecraft/network/play/client/CPacketPlayer$Rotation");
                    G = A5.a("net/minecraft/network/play/client/CPacketPlayer$Position");
                    bH = A5.a("net/minecraft/network/play/client/CPacketPlayer$PositionRotation");
                    bd = A5.a("net/minecraft/entity/MoverType");
                    ab = A5.a("net/minecraft/util/SoundEvent");
                    a6 = A5.a("net/minecraft/util/EnumHand");
                    cy = A5.a("net/minecraft/inventory/ClickType");
                    a_ = A5.a("net/minecraft/util/EnumActionResult");
                    E = A5.a("net/minecraft/util/NonNullList");
                    cb = A5.a("net/minecraft/inventory/EntityEquipmentSlot");
                    x = A5.a("net/minecraft/potion/PotionUtils");
                    c8 = A5.a("net/minecraft/item/ItemSplashPotion");
                    bZ = A5.a("net/minecraft/tileentity/TileEntityShulkerBox");
                    if (n10 != 0) break block19;
                }
                aW = A5.a("net/minecraft/util/Vec3");
                b4 = A5.a("net/minecraft/util/AxisAlignedBB");
                cH = A5.a("net/minecraft/util/MovingObjectPosition");
                d = A5.a("net/minecraft/util/MovingObjectPosition$MovingObjectType");
                W = A5.a("net/minecraft/network/play/client/C00PacketKeepAlive");
                j = A5.a("net/minecraft/network/play/client/C0FPacketConfirmTransaction");
                cp = A5.a("net/minecraft/network/play/client/C0APacketAnimation");
                cq = A5.a("net/minecraft/network/play/client/C0BPacketEntityAction");
                dQ = A5.a("net/minecraft/network/play/client/C01PacketChatMessage");
                cU = A5.a("net/minecraft/network/play/client/C02PacketUseEntity");
                bN = A5.a("net/minecraft/network/play/client/C03PacketPlayer");
                aB = A5.a("net/minecraft/network/play/client/C07PacketPlayerDigging");
                bF = A5.a("net/minecraft/network/play/client/C09PacketHeldItemChange");
                a5 = A5.a("net/minecraft/network/play/client/C13PacketPlayerAbilities");
                a3 = A5.a("net/minecraft/network/play/client/C0DPacketCloseWindow");
                ax = A5.a("net/minecraft/client/renderer/entity/RenderItem");
                b7 = A5.a("net/minecraft/network/play/client/C02PacketUseEntity$Action");
                de = A5.a("net/minecraft/entity/ai/attributes/BaseAttributeMap");
                bG = A5.a("net/minecraft/util/IChatComponent");
                b3 = A5.a("net/minecraft/util/ChatComponentText");
                aI = A5.a("net/minecraft/util/ChatComponentStyle");
                bR = A5.a("net/minecraft/util/ChatComponentTranslation");
                cu = A5.a("net/minecraft/client/renderer/WorldRenderer");
                ct = A5.a("net/minecraft/network/play/server/S2APacketParticles");
                cJ = A5.a("net/minecraft/network/play/server/S27PacketExplosion");
                cQ = A5.a("net/minecraft/network/play/server/S12PacketEntityVelocity");
                R = A5.a("net/minecraft/network/play/server/S14PacketEntity");
                bk = A5.a("net/minecraft/network/play/server/S14PacketEntity$S16PacketEntityLook");
                bI = A5.a("net/minecraft/network/play/server/S23PacketBlockChange");
                bp = A5.a("net/minecraft/network/play/server/S18PacketEntityTeleport");
                U = A5.a("net/minecraft/network/play/server/S08PacketPlayerPosLook");
                b2 = A5.a("net/minecraft/client/renderer/entity/RendererLivingEntity");
                bm = A5.a("net/minecraft/util/RegistryNamespaced");
                z = A5.a("net/minecraft/util/RegistrySimple");
                cz = A5.a("net/minecraftforge/event/entity/player/PlayerInteractEvent$Action");
                dE = A5.a("net/minecraft/network/play/client/C03PacketPlayer$C05PacketPlayerLook");
                G = A5.a("net/minecraft/network/play/client/C03PacketPlayer$C04PacketPlayerPosition");
                bH = A5.a("net/minecraft/network/play/client/C03PacketPlayer$C06PacketPlayerPosLook");
                K = A5.a("net/minecraft/client/particle/EffectRenderer");
                V = A5.a("net/minecraft/client/particle/EntityParticleEmitter");
                bL = A5.a("net/minecraft/client/particle/EntityFX");
                dB = A5.a("net/minecraft/client/particle/EntityCritFX");
                n6 = 1216;
            }
            cG = A5.a(a.a.cs(n6));
        }
        bE = A5.a("net/minecraftforge/client/event/RenderHandEvent");
        bA = A5.a("com/google/common/collect/Multimap");
        cR = A5.a("com/google/common/collect/Lists");
        aO = A5.a("com/google/common/collect/Ordering");
        cO = A5.a("com/google/common/base/Predicate");
    }

    static {
        C = new HashMap();
        A5.b(false);
    }

    public static void b(boolean bl) {
        v = bl;
    }

    public static boolean d() {
        return v;
    }

    public static boolean c() {
        boolean bl = A5.d();
        return !bl;
    }

    private static CodeAttribute$RuntimeCopyException a(CodeAttribute$RuntimeCopyException codeAttribute$RuntimeCopyException) {
        return codeAttribute$RuntimeCopyException;
    }
}

