/*
 * Decompiled with CFR 0.152.
 */
package manthe;

import java.util.ArrayList;
import java.util.List;
import javassist.bytecode.CodeAttribute$RuntimeCopyException;
import manthe.A5;
import manthe.V;
import manthe.cy_0;
import manthe.g6;
import manthe.g8;
import manthe.gB;
import manthe.gE;
import manthe.gF;
import manthe.gJ;
import manthe.gL;
import manthe.gP;
import manthe.gR;
import manthe.gT;
import manthe.gX;
import manthe.gY;
import manthe.gm_0;
import manthe.gr_0;
import manthe.gs_0;
import manthe.gv_0;
import manthe.h0;
import manthe.h1;
import manthe.h2;
import manthe.h3;
import manthe.h4;
import manthe.h5;
import manthe.h6;
import manthe.h8;
import manthe.h9;
import manthe.hA;
import manthe.hB;
import manthe.hC;
import manthe.hD;
import manthe.hE;
import manthe.hF;
import manthe.hG;
import manthe.hH;
import manthe.hI;
import manthe.hJ;
import manthe.hK;
import manthe.hL;
import manthe.hM;
import manthe.hN;
import manthe.hO;
import manthe.hP;
import manthe.hQ;
import manthe.hR;
import manthe.hS;
import manthe.hT;
import manthe.hU;
import manthe.hV;
import manthe.hW;
import manthe.hX;
import manthe.hY;
import manthe.hZ;
import manthe.h_;
import manthe.ha_0;
import manthe.hb_0;
import manthe.hc_0;
import manthe.hd_0;
import manthe.he_0;
import manthe.hf_0;
import manthe.hg_0;
import manthe.hh_0;
import manthe.hi_0;
import manthe.hj_0;
import manthe.hk_0;
import manthe.hl_0;
import manthe.hm_0;
import manthe.ho_0;
import manthe.hp_0;
import manthe.hq_0;
import manthe.hr_0;
import manthe.hs_0;
import manthe.ht_0;
import manthe.hu_0;
import manthe.hv_0;
import manthe.hw_0;
import manthe.hx_0;
import manthe.hy_0;
import manthe.hz_0;
import manthe.i0;
import manthe.i1;
import manthe.i2;
import manthe.i3;
import manthe.i4;
import manthe.i5;
import manthe.i6;
import manthe.i7;
import manthe.i8;
import manthe.i9;
import manthe.iA;
import manthe.iB;
import manthe.iE;
import manthe.iF;
import manthe.iG;
import manthe.iH;
import manthe.iI;
import manthe.iJ;
import manthe.iK;
import manthe.iL;
import manthe.iM;
import manthe.iN;
import manthe.iO;
import manthe.iP;
import manthe.iQ;
import manthe.iR;
import manthe.iS;
import manthe.iT;
import manthe.iU;
import manthe.iV;
import manthe.iW;
import manthe.iX;
import manthe.iY;
import manthe.iZ;
import manthe.i_;
import manthe.ia_0;
import manthe.ib_0;
import manthe.ic_0;
import manthe.id_0;
import manthe.ie_0;
import manthe.ig_0;
import manthe.ih_0;
import manthe.ij_0;
import manthe.ik_0;
import manthe.il_0;
import manthe.im_0;
import manthe.in_0;
import manthe.io_0;
import manthe.ip_0;
import manthe.ir_0;
import manthe.is_0;
import manthe.it_0;
import manthe.iu_0;
import manthe.iv_0;
import manthe.iw_0;
import manthe.ix_0;
import manthe.iy_0;
import manthe.iz_0;
import manthe.j0;
import manthe.j1;
import manthe.j2;
import manthe.j3;
import manthe.j4;
import manthe.j5;
import manthe.j6;
import manthe.j7;
import manthe.j8;
import manthe.j9;
import manthe.jA;
import manthe.jB;
import manthe.jC;
import manthe.jD;
import manthe.jE;
import manthe.jF;
import manthe.jH;
import manthe.jI;
import manthe.jJ;
import manthe.jK;
import manthe.jL;
import manthe.jM;
import manthe.jO;
import manthe.jP;
import manthe.jQ;
import manthe.jR;
import manthe.jS;
import manthe.jT;
import manthe.jU;
import manthe.jV;
import manthe.jW;
import manthe.jX;
import manthe.jY;
import manthe.jZ;
import manthe.j_;
import manthe.ja_0;
import manthe.jb_0;
import manthe.jc_0;
import manthe.jd_0;
import manthe.je_0;
import manthe.jf_0;
import manthe.jg_0;
import manthe.jh_0;
import manthe.jj_0;
import manthe.jk_0;
import manthe.jl_0;
import manthe.jm_0;
import manthe.jn_0;
import manthe.jo_0;
import manthe.jp_0;
import manthe.jq_0;
import manthe.jr_0;
import manthe.js_0;
import manthe.jt_0;
import manthe.ju_0;
import manthe.jv_0;
import manthe.jw_0;
import manthe.jx_0;
import manthe.jy_0;
import manthe.jz_0;
import manthe.k3;
import manthe.k7;
import manthe.kI;
import manthe.kM;
import manthe.kQ;
import manthe.kg_0;
import manthe.kk_0;
import manthe.ko_0;
import manthe.on;

/*
 * Renamed from manthe.t
 */
public class t_0 {
    public static List<gJ> b_ = new ArrayList<gJ>();
    public h5 bW;
    public hC aA;
    public hA ca;
    public jP g;
    public iz_0 e;
    public iw_0 am;
    public i_ M;
    public ie_0 a0;
    public ix_0 b;
    public iA aF;
    public he_0 aJ;
    public it_0 aL;
    public kI s;
    public hE d;
    public hx_0 bC;
    public hQ U;
    public hk_0 c;
    public ho_0 R;
    public jy_0 Y;
    public hm_0 bA;
    public jD a_;
    public kg_0 V;
    public jj_0 bZ;
    public j0 cu;
    public hb_0 aU;
    public h6 X;
    public h2 bj;
    public jC bN;
    public jT aM;
    public id_0 br;
    public i6 au;
    public iT u;
    public hr_0 bz;
    public hL av;
    public is_0 h;
    public iX b5;
    public gB aa;
    public gm_0 q;
    public gX aY;
    public gE cq;
    public h3 P;
    public iV aQ;
    public io_0 z;
    public hc_0 b0;
    public gP b9;
    public hS bP;
    public hO a;
    public hU bY;
    public g8 bh;
    public g6 a1;
    public gs_0 bG;
    public i1 bq;
    public hP b7;
    public ir_0 an;
    public ht_0 aP;
    public hq_0 aw;
    public j7 cr;
    public jK Z;
    public jw_0 B;
    public jk_0 aX;
    public j9 bR;
    public jb_0 aB;
    public j4 bp;
    public jh_0 bK;
    public jf_0 a4;
    public j1 aT;
    public jl_0 as;
    public jz_0 bT;
    public jH o;
    public jS cp;
    public jU ad;
    public ju_0 bH;
    public hW bb;
    public hh_0 bS;
    public jQ ao;
    public ko_0 co;
    public jo_0 ap;
    public j3 b8;
    public ik_0 cj;
    public hJ i;
    public im_0 aV;
    public jp_0 be;
    public jW m;
    public jV cc;
    public jX ce;
    public ic_0 bx;
    public i5 aI;
    public iu_0 j;
    public iE bO;
    public ig_0 b2;
    public il_0 bf;
    public jq_0 ck;
    public jE aN;
    public hF ae;
    public gr_0 cw;
    public gL bt;
    public je_0 L;
    public iI ag;
    public i7 ak;
    public i9 F;
    public iG bs;
    public jd_0 a5;
    public jc_0 v;
    public hu_0 bd;
    public k7 O;
    public gY bV;
    public ij_0 bk;
    public iy_0 C;
    public in_0 bU;
    public iN cy;
    public iZ bE;
    public jM W;
    public jg_0 H;
    public jt_0 ay;
    public jZ N;
    public j_ ac;
    public gv_0 I;
    public ia_0 a2;
    public jL a3;
    public iL aE;
    public hV ch;
    public iM aG;
    public jn_0 T;
    public ja_0 ai;
    public jI b4;
    public jF S;
    public h9 bB;
    public jJ cz;
    public gR bI;
    public k3 bF;
    public kQ bo;
    public h_ bQ;
    public kM a6;
    public hs_0 aC;
    public h8 cl;
    public hB ah;
    public hR cx;
    public iW bD;
    public ih_0 Q;
    public jY a9;
    public jv_0 w;
    public h4 ax;
    public iJ aS;
    public i2 aH;
    public hl_0 bg;
    public hg_0 x;
    public hI bM;
    public hM K;
    public jB D;
    public jR bu;
    public iU bi;
    public i8 bJ;
    public iB cd;
    public ip_0 ct;
    public hy_0 bm;
    public h0 E;
    public hw_0 n;
    public hz_0 cs;
    public jx_0 ci;
    public jA bn;
    public js_0 bw;
    public jO cm;
    public ib_0 G;
    public i4 aO;
    public gT at;
    public hj_0 bc;
    public j8 bv;
    public iv_0 cn;
    public iY b1;
    public iP aW;
    public iF ab;
    public jr_0 r;
    public j2 az;
    public iR aR;
    public hG cv;
    public hd_0 ba;
    public i0 bX;
    public gF aq;
    public j6 af;
    public iO k;
    public hi_0 a7;
    public kk_0 J;
    public jm_0 bl;
    public hX aZ;
    public iS b6;
    public iK aD;
    public iH p;
    public iQ a8;
    public i3 cf;
    public hT by;
    public hD y;
    public hf_0 A;
    public hK cb;
    public h1 b3;
    public hH cg;
    public hZ bL;
    public ha_0 aj;
    public hN l;
    public j5 f;
    public hp_0 ar;
    public hv_0 al;
    public hY t;
    private static String[] aK;

    public void c() {
        block20: {
            int n6;
            block19: {
                block18: {
                    block17: {
                        block16: {
                            block15: {
                                block14: {
                                    n6 = gJ.b();
                                    if (n6 != 0) {
                                        if (!on.p.h()) {
                                            this.U = new hQ();
                                            this.c = new hk_0();
                                            this.R = new ho_0();
                                            this.aU = new hb_0();
                                            this.q = new gm_0();
                                            this.aY = new gX();
                                            this.cq = new gE();
                                            this.P = new h3();
                                            this.b9 = new gP();
                                            this.bh = new g8();
                                            this.a1 = new g6();
                                            this.bb = new hW();
                                            this.bS = new hh_0();
                                            this.bV = new gY();
                                            this.at = new gT();
                                            this.I = new gv_0();
                                            this.ch = new hV();
                                            this.bB = new h9();
                                            this.bI = new gR();
                                            this.ax = new h4();
                                            this.bg = new hl_0();
                                            this.bM = new hI();
                                            this.K = new hM();
                                            this.x = new hg_0();
                                            this.n = new hw_0();
                                            this.cs = new hz_0();
                                            this.cv = new hG();
                                            this.bG = new gs_0();
                                            this.bd = new hu_0();
                                            this.O = new k7();
                                            t_0 t_02 = this;
                                            if (n6 != 0) {
                                                t_02.aq = new gF();
                                                if (manthe.V.c() > 13) {
                                                    this.aa = new gB();
                                                }
                                                t_02 = this;
                                            }
                                            t_02.ct = new ip_0();
                                        }
                                        this.bW = new h5();
                                        this.aA = new hC();
                                        this.ca = new hA();
                                        this.g = new jP();
                                        this.e = new iz_0();
                                        this.am = new iw_0();
                                        this.M = new i_();
                                        this.a0 = new ie_0();
                                        this.b = new ix_0();
                                        this.aF = new iA();
                                        this.aJ = new he_0();
                                        this.aL = new it_0();
                                        this.s = new kI();
                                        this.d = new hE();
                                        this.bC = new hx_0();
                                        this.Y = new jy_0();
                                        this.bA = new hm_0();
                                        this.a_ = new jD();
                                        this.bZ = new jj_0();
                                        this.cu = new j0();
                                        this.X = new h6();
                                        this.bj = new h2();
                                        this.aM = new jT();
                                        this.br = new id_0();
                                        this.au = new i6();
                                        this.u = new iT();
                                        this.bz = new hr_0();
                                        this.av = new hL();
                                        this.h = new is_0();
                                        this.b5 = new iX();
                                        this.aQ = new iV();
                                        this.z = new io_0();
                                        this.cl = new h8();
                                        this.b0 = new hc_0();
                                        this.bP = new hS();
                                        this.a = new hO();
                                        this.bq = new i1();
                                        this.an = new ir_0();
                                        this.aP = new ht_0();
                                        this.cr = new j7();
                                        this.B = new jw_0();
                                        this.Z = new jK();
                                        this.aX = new jk_0();
                                        this.bK = new jh_0();
                                        this.bp = new j4();
                                        this.aB = new jb_0();
                                        this.bR = new j9();
                                        this.bT = new jz_0();
                                        this.o = new jH();
                                        this.a4 = new jf_0();
                                        this.aT = new j1();
                                        this.ad = new jU();
                                        this.bH = new ju_0();
                                        this.ao = new jQ();
                                        this.co = new ko_0();
                                        this.ap = new jo_0();
                                        this.b8 = new j3();
                                        this.cj = new ik_0();
                                        this.i = new hJ();
                                        this.aV = new im_0();
                                        this.be = new jp_0();
                                        this.m = new jW();
                                        this.cc = new jV();
                                        this.ce = new jX();
                                        this.bx = new ic_0();
                                        this.aI = new i5();
                                        this.j = new iu_0();
                                        this.bO = new iE();
                                        this.b2 = new ig_0();
                                        this.bf = new il_0();
                                        this.ck = new jq_0();
                                        this.aN = new jE();
                                        this.bt = new gL();
                                        this.cw = new gr_0();
                                        this.L = new je_0();
                                        this.ag = new iI();
                                        this.a5 = new jd_0();
                                        this.v = new jc_0();
                                        this.bk = new ij_0();
                                        this.C = new iy_0();
                                        this.bU = new in_0();
                                        this.cy = new iN();
                                        this.bE = new iZ();
                                        this.W = new jM();
                                        this.H = new jg_0();
                                        this.ay = new jt_0();
                                        this.N = new jZ();
                                        this.a2 = new ia_0();
                                        this.a3 = new jL();
                                        this.aE = new iL();
                                        this.aG = new iM();
                                        this.T = new jn_0();
                                        this.b4 = new jI();
                                        this.S = new jF();
                                        this.cz = new jJ();
                                        this.r = new jr_0();
                                        this.az = new j2();
                                        this.bF = new k3();
                                        this.bo = new kQ();
                                        this.bQ = new h_();
                                        this.aC = new hs_0();
                                        this.ah = new hB();
                                        this.Q = new ih_0();
                                        this.bD = new iW();
                                        this.a9 = new jY();
                                        this.w = new jv_0();
                                        this.aS = new iJ();
                                        this.aH = new i2();
                                        this.ci = new jx_0();
                                        this.bn = new jA();
                                        this.cm = new jO();
                                        this.ai = new ja_0();
                                        this.bw = new js_0();
                                        this.G = new ib_0();
                                        this.aO = new i4();
                                        this.cn = new iv_0();
                                        this.b1 = new iY();
                                        this.aW = new iP();
                                        this.ab = new iF();
                                        this.aR = new iR();
                                        this.ba = new hd_0();
                                        this.bX = new i0();
                                        this.k = new iO();
                                        this.aZ = new hX();
                                        this.b6 = new iS();
                                        this.aD = new iK();
                                        this.p = new iH();
                                        this.bL = new hZ();
                                        this.f = new j5();
                                    }
                                    if (n6 == 0) break block14;
                                    if (A5.dR == null) break block15;
                                    this.J = new kk_0();
                                }
                                on.D = true;
                            }
                            if (manthe.V.c() <= 13) break block16;
                            this.a8 = new iQ();
                            this.cf = new i3();
                            this.by = new hT();
                            this.cp = new jS();
                            this.bc = new hj_0();
                            this.ac = new j_();
                            this.V = new kg_0();
                            this.bN = new jC();
                            this.bY = new hU();
                            this.b7 = new hP();
                            this.as = new jl_0();
                            this.ae = new hF();
                            this.ak = new i7();
                            this.F = new i9();
                            this.bs = new iG();
                            this.a6 = new kM();
                            this.cx = new hR();
                            this.D = new jB();
                            this.ai = new ja_0();
                            this.E = new h0();
                            this.D = new jB();
                            this.bl = new jm_0();
                            this.aj = new ha_0();
                            this.l = new hN();
                            this.ar = new hp_0();
                            this.al = new hv_0();
                            this.t = new hY();
                            if (n6 != 0) break block17;
                        }
                        this.y = new hD();
                        this.aw = new hq_0();
                    }
                    if (manthe.V.c() < 23) break block18;
                    this.bi = new iU();
                    this.bu = new jR();
                    this.bJ = new i8();
                    this.cd = new iB();
                    this.bv = new j8();
                    this.af = new j6();
                    this.a7 = new hi_0();
                    if (n6 != 0) break block19;
                }
                this.bm = new hy_0();
            }
            if (A5.bA != null) {
                this.A = new hf_0();
                this.cb = new hK();
                this.b3 = new h1();
            }
            this.cg = new hH();
            if (cy_0.c()) break block20;
            gJ.b(++n6);
        }
    }

    static {
        t_0.b(new String[4]);
    }

    public static void b(String[] stringArray) {
        aK = stringArray;
    }

    public static String[] b() {
        return aK;
    }

    private static CodeAttribute$RuntimeCopyException a(CodeAttribute$RuntimeCopyException codeAttribute$RuntimeCopyException) {
        return codeAttribute$RuntimeCopyException;
    }
}

